nome_carro = input("digite o nome do carro: ")
valor_carro = float(input("digite o valor do carro: ")) 
consumo_por_litro = float(input("digite o consumo por litro: "))
print("-" * 40)
print(f"| carro: {nome_carro}")
print(f"| valor: {valor_carro}")
print(f"| consumo por litro: {consumo_por_litro}")
print("-" * 40)